// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculateLookupMatrix
NumericMatrix calculateLookupMatrix(int length, NumericMatrix daten, NumericMatrix lookup);
RcppExport SEXP _cramer_calculateLookupMatrix(SEXP lengthSEXP, SEXP datenSEXP, SEXP lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type daten(datenSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lookup(lookupSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateLookupMatrix(length, daten, lookup));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cramer_calculateLookupMatrix", (DL_FUNC) &_cramer_calculateLookupMatrix, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_cramer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
